<a href="https://colab.research.google.com/github/jcjimenezb123/PFM_PronosticoDemanda/blob/master/RecVta2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

In [23]:
#se cargan las ventas y existencias
df=pd.read_csv('ID_REC - 2021_11_04.csv', parse_dates=['FECHA'],dayfirst=True)
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736481 entries, 0 to 736480
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ULT_SUST_DEF   736481 non-null  int64
 1   TALLA_INI_MIN  736481 non-null  int64
 2   TALLA_FIN_MAX  736481 non-null  int64
 3   TI_CVE_N       736481 non-null  int64
 4   TA_CVE_N       736481 non-null  float64
 5   FECHA          736481 non-null  datetime64[ns]
 6   EXIST          736481 non-null  int64
 7   VENTA          736481 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(6)
memory usage: 45.0 MB

In [24]:
df.head()

   ULT_SUST_DEF  TALLA_INI_MIN  TALLA_FIN_MAX  ...      FECHA  EXIST VENTA
0        127399             22             27  ... 2021-07-01      0     0
1        127399             22             27  ... 2021-07-02      0     0
2        127399             22             27  ... 2021-07-03      0     0
3        127399             22             27  ... 2021-07-04      0     0
4        127399             22             27  ... 2021-07-05      0     0

[5 rows x 8 columns]

In [25]:
df.describe()

        ULT_SUST_DEF  TALLA_INI_MIN  ...          EXIST          VENTA
count  736481.000000  736481.000000  ...  736481.000000  736481.000000
mean   815566.844316      21.122610  ...       4.658530       0.112105
std    246016.218994       0.327989  ...       8.015219       0.455760
min    127399.000000      21.000000  ...       0.000000      -3.000000
25%    828517.000000      21.000000  ...       1.000000       0.000000
50%    879753.000000      21.000000  ...       2.000000       0.000000
75%    977292.000000      21.000000  ...       5.000000       0.000000
max    990481.000000      22.000000  ...     175.000000      11.000000

[8 rows x 7 columns]

In [26]:
df[df['EXIST']==0].count()

ULT_SUST_DEF     181219
TALLA_INI_MIN    181219
TALLA_FIN_MAX    181219
TI_CVE_N         181219
TA_CVE_N         181219
FECHA            181219
EXIST            181219
VENTA            181219
dtype: int64

In [27]:
df[df['VENTA']<0].count()

ULT_SUST_DEF     10321
TALLA_INI_MIN    10321
TALLA_FIN_MAX    10321
TI_CVE_N         10321
TA_CVE_N         10321
FECHA            10321
EXIST            10321
VENTA            10321
dtype: int64

In [28]:
df[(df['EXIST']==0)&(df['VENTA']>0)].count()

ULT_SUST_DEF     489
TALLA_INI_MIN    489
TALLA_FIN_MAX    489
TI_CVE_N         489
TA_CVE_N         489
FECHA            489
EXIST            489
VENTA            489
dtype: int64

In [29]:
df['VENTA']=df.apply(lambda x: np.NAN if x['EXIST'] == 0 else x['VENTA'],axis=1)
df

        ULT_SUST_DEF  TALLA_INI_MIN  TALLA_FIN_MAX  ...      FECHA  EXIST VENTA
0             127399             22             27  ... 2021-07-01      0   NaN
1             127399             22             27  ... 2021-07-02      0   NaN
2             127399             22             27  ... 2021-07-03      0   NaN
3             127399             22             27  ... 2021-07-04      0   NaN
4             127399             22             27  ... 2021-07-05      0   NaN
...              ...            ...            ...  ...        ...    ...   ...
736476        990481             21             28  ... 2021-10-09      1   0.0
736477        990481             21             28  ... 2021-10-10      1   0.0
736478        990481             21             28  ... 2021-10-11      1   0.0
736479        990481             21             28  ... 2021-10-12      1   0.0
736480        990481             21             28  ... 2021-10-13      1   0.0

[736481 rows x 8 columns]

In [30]:
#se obtiene el dia de la semana
df['dia_semana'] = df['FECHA'].dt.day_name()
#df['semana']=df['fecha'].dt.week
df['desde']=df['FECHA'].dt.to_period('W').dt.start_time
df

        ULT_SUST_DEF  TALLA_INI_MIN  TALLA_FIN_MAX  ...  VENTA  dia_semana      desde
0             127399             22             27  ...    NaN    Thursday 2021-06-28
1             127399             22             27  ...    NaN      Friday 2021-06-28
2             127399             22             27  ...    NaN    Saturday 2021-06-28
3             127399             22             27  ...    NaN      Sunday 2021-06-28
4             127399             22             27  ...    NaN      Monday 2021-07-05
...              ...            ...            ...  ...    ...         ...        ...
736476        990481             21             28  ...    0.0    Saturday 2021-10-04
736477        990481             21             28  ...    0.0      Sunday 2021-10-04
736478        990481             21             28  ...    0.0      Monday 2021-10-11
736479        990481             21             28  ...    0.0     Tuesday 2021-10-11
736480        990481             21             28  ...    0.0   Wednesday 2021-10-11

[736481 rows x 10 columns]

In [31]:
#se obtiene una mustra de un modelo talla
idtalla=df[(df['ULT_SUST_DEF']==127399) & (df['TA_CVE_N']==22) & (df['TI_CVE_N']==1)]
idtalla.sort_values(by=['FECHA'],inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [32]:
import plotly.express as px

fig = px.line(idtalla, x="FECHA", y="VENTA")
fig.add_scatter(x=idtalla['FECHA'], y=idtalla['EXIST'], mode='lines')
fig.show()

In [33]:
fig = px.scatter(idtalla, x="FECHA", y="VENTA",marginal_y='histogram')
fig.show()

In [34]:
df.sort_values(by=['TI_CVE_N','ULT_SUST_DEF','TA_CVE_N','dia_semana','FECHA'],inplace=True)
df

        ULT_SUST_DEF  TALLA_INI_MIN  TALLA_FIN_MAX  ...  VENTA  dia_semana      desde
1             127399             22             27  ...    NaN      Friday 2021-06-28
8             127399             22             27  ...    0.0      Friday 2021-07-05
15            127399             22             27  ...    0.0      Friday 2021-07-12
22            127399             22             27  ...    0.0      Friday 2021-07-19
29            127399             22             27  ...    0.0      Friday 2021-07-26
...              ...            ...            ...  ...    ...         ...        ...
736452        990481             21             28  ...    0.0   Wednesday 2021-09-13
736459        990481             21             28  ...    0.0   Wednesday 2021-09-20
736466        990481             21             28  ...    0.0   Wednesday 2021-09-27
736473        990481             21             28  ...    0.0   Wednesday 2021-10-04
736480        990481             21             28  ...    0.0   Wednesday 2021-10-11

[736481 rows x 10 columns]

In [35]:
#Se observan los negados
df.head(30).style.applymap(lambda x: None if x==x else 'color: red')

In [36]:
df.interpolate(method='linear', limit_direction='both',inplace=True)
df.head(30)

     ULT_SUST_DEF  TALLA_INI_MIN  TALLA_FIN_MAX  ...  VENTA  dia_semana      desde
1          127399             22             27  ...    0.0      Friday 2021-06-28
8          127399             22             27  ...    0.0      Friday 2021-07-05
15         127399             22             27  ...    0.0      Friday 2021-07-12
22         127399             22             27  ...    0.0      Friday 2021-07-19
29         127399             22             27  ...    0.0      Friday 2021-07-26
36         127399             22             27  ...    0.0      Friday 2021-08-02
43         127399             22             27  ...    0.0      Friday 2021-08-09
50         127399             22             27  ...    0.0      Friday 2021-08-16
57         127399             22             27  ...    0.0      Friday 2021-08-23
64         127399             22             27  ...    0.0      Friday 2021-08-30
71         127399             22             27  ...    0.0      Friday 2021-09-06
78         127399             22             27  ...    0.0      Friday 2021-09-13
85         127399             22             27  ...    1.0      Friday 2021-09-20
92         127399             22             27  ...    0.0      Friday 2021-09-27
99         127399             22             27  ...    0.0      Friday 2021-10-04
106        127399             22             27  ...    0.0      Friday 2021-10-11
113        127399             22             27  ...    0.0      Friday 2021-10-18
120        127399             22             27  ...    0.0      Friday 2021-10-25
4          127399             22             27  ...    0.0      Monday 2021-07-05
11         127399             22             27  ...    0.0      Monday 2021-07-12
18         127399             22             27  ...    0.0      Monday 2021-07-19
25         127399             22             27  ...    0.0      Monday 2021-07-26
32         127399             22             27  ...    0.0      Monday 2021-08-02
39         127399             22             27  ...    0.0      Monday 2021-08-09
46         127399             22             27  ...    0.0      Monday 2021-08-16
53         127399             22             27  ...    0.0      Monday 2021-08-23
60         127399             22             27  ...    0.0      Monday 2021-08-30
67         127399             22             27  ...    0.0      Monday 2021-09-06
74         127399             22             27  ...    0.0      Monday 2021-09-13
81         127399             22             27  ...    0.0      Monday 2021-09-20

[30 rows x 10 columns]

In [37]:
df.sort_values(by=['TI_CVE_N','ULT_SUST_DEF','TA_CVE_N','FECHA'],inplace=True)
df

        ULT_SUST_DEF  TALLA_INI_MIN  TALLA_FIN_MAX  ...  VENTA  dia_semana      desde
0             127399             22             27  ...    0.0    Thursday 2021-06-28
1             127399             22             27  ...    0.0      Friday 2021-06-28
2             127399             22             27  ...    0.0    Saturday 2021-06-28
3             127399             22             27  ...    0.0      Sunday 2021-06-28
4             127399             22             27  ...    0.0      Monday 2021-07-05
...              ...            ...            ...  ...    ...         ...        ...
736476        990481             21             28  ...    0.0    Saturday 2021-10-04
736477        990481             21             28  ...    0.0      Sunday 2021-10-04
736478        990481             21             28  ...    0.0      Monday 2021-10-11
736479        990481             21             28  ...    0.0     Tuesday 2021-10-11
736480        990481             21             28  ...    0.0   Wednesday 2021-10-11

[736481 rows x 10 columns]

In [38]:
df.describe()

        ULT_SUST_DEF  TALLA_INI_MIN  ...          EXIST          VENTA
count  736481.000000  736481.000000  ...  736481.000000  736481.000000
mean   815566.844316      21.122610  ...       4.658530       0.152997
std    246016.218994       0.327989  ...       8.015219       0.483472
min    127399.000000      21.000000  ...       0.000000      -3.000000
25%    828517.000000      21.000000  ...       1.000000       0.000000
50%    879753.000000      21.000000  ...       2.000000       0.000000
75%    977292.000000      21.000000  ...       5.000000       0.000000
max    990481.000000      22.000000  ...     175.000000      11.000000

[8 rows x 7 columns]